@startuml
allowmixing
class DVD {
+ getDetails()
}
class DVDRepository {
+ save(DVD)
}
actor "Cineast" as cine
actor "Admin" as db

db -> DVDRepository::save

DVDRepository .> DVD : uses

cine -> DVD::getDetails

@enduml
